#define BACKLIGHT_PWM_DRIVER PWMD5
#define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_B  /* For GP11*/

#define BACKLIGHT_PIN GP11
#define BACKLIGHT_LEVELS 4
#define BACKLIGHT_ON_STATE 0
#define BACKLIGHT_DEFAULT_ON 1
#define BACKLIGHT_DEFAULT_LEVEL 2
